title: Yongliang Xu's Homepage
page-top-title: Yongliang Xu
top-section-bg-text: Mathematics
home-subtitle: Yongliang Xu&ensp;|&ensp;许永亮
copyright-text: '&copy; Yongliang Xu 2025-2027. All Rights Reserved.'
